version: '3.8'

services:
  python:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.backend=${podName}-python"
      - "traefik.frontend.rule=Host:${hostRule}"
      - "traefik.docker.network=${podName}_frontend"
      - "traefik.port=5000"

    networks:
      - frontend

    volumes:
      - ./data:/app/files_from_server

networks:
  frontend: